<?php
/**
 * EventBestCustomersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MailchimpMinimal
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.9
 * Contact: apihelp@mailchimp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.12
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MailchimpMinimal;

/**
 * EventBestCustomersTest Class Doc Comment
 *
 * @category    Class
 * @description Settings for a Best Customers workflow.
 * @package     MailchimpMinimal
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EventBestCustomersTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EventBestCustomers"
     */
    public function testEventBestCustomers()
    {
    }

    /**
     * Test attribute "send_immediately"
     */
    public function testPropertySendImmediately()
    {
    }

    /**
     * Test attribute "purchase_orders"
     */
    public function testPropertyPurchaseOrders()
    {
    }

    /**
     * Test attribute "lifetime_purchase_value"
     */
    public function testPropertyLifetimePurchaseValue()
    {
    }
}
